using System.Text;
using System.Text.Json;
using Microsoft.Build.Framework;

namespace Sbroenne.ExcelMcp.Build.Tasks;

/// <summary>Writes machine-readable and human-readable macOS action inventories.</summary>
public sealed class GenerateMacActionInventory : Microsoft.Build.Utilities.Task
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    /// <summary>Generated C# source containing the authoritative JSON constant.</summary>
    [Required]
    public string ManifestPath { get; set; } = string.Empty;

    /// <summary>Destination for the generated JSON inventory.</summary>
    [Required]
    public string JsonOutputPath { get; set; } = string.Empty;

    /// <summary>Destination for the generated Markdown inventory.</summary>
    [Required]
    public string MarkdownOutputPath { get; set; } = string.Empty;

    /// <inheritdoc />
    public override bool Execute()
    {
        try
        {
            var source = File.ReadAllText(ManifestPath);
            var json = ExtractJson(source);
            var actions = JsonSerializer.Deserialize<List<MacAction>>(json, JsonOptions)
                ?? throw new InvalidDataException("The generated macOS action inventory is empty.");

            Directory.CreateDirectory(Path.GetDirectoryName(JsonOutputPath)!);
            Directory.CreateDirectory(Path.GetDirectoryName(MarkdownOutputPath)!);
            File.WriteAllText(JsonOutputPath, json, new UTF8Encoding(false));
            File.WriteAllText(MarkdownOutputPath, RenderMarkdown(actions), new UTF8Encoding(false));
            Log.LogMessage(
                MessageImportance.High,
                $"Generated macOS action inventory: {actions.Count} operations.");
            return true;
        }
        catch (Exception exception)
        {
            Log.LogErrorFromException(exception, showStackTrace: true);
            return false;
        }
    }

    private static string ExtractJson(string source)
    {
        const string startMarker = "public const string Json = @\"";
        const string endMarker = "\";";
        var start = source.IndexOf(startMarker, StringComparison.Ordinal);
        if (start < 0)
        {
            throw new InvalidDataException("Generated macOS inventory JSON constant was not found.");
        }

        start += startMarker.Length;
        var end = source.LastIndexOf(endMarker, StringComparison.Ordinal);
        if (end <= start)
        {
            throw new InvalidDataException("Generated macOS inventory JSON constant is incomplete.");
        }

        return source.Substring(start, end - start).Replace("\"\"", "\"");
    }

    private static string RenderMarkdown(IReadOnlyList<MacAction> actions)
    {
        var builder = new StringBuilder();
        builder.AppendLine("# macOS action inventory");
        builder.AppendLine();
        builder.AppendLine(
            "Generated from Core `[ServiceCategory]`, `[ServiceAction]`, and `[MacCapability]` metadata. " +
            "Do not edit this table directly; update the source contract or generator metadata.");
        builder.AppendLine();
        builder.AppendLine(
            "The companion [`macos-action-inventory.json`](generated/macos-action-inventory.json) " +
            "is the machine-readable source generated by the same build step.");
        builder.AppendLine();
        builder.AppendLine(
            "`Partial` means the selected implementation exists but remains gated on its recorded " +
            "real-Excel acceptance step. `Blocked` means the reviewed Apple Events and Office.js " +
            "surfaces cannot preserve the exact public contract; use the recorded alternative.");
        builder.AppendLine();
        var enabledCount = actions.Count(action => action.IsAvailable);
        builder.AppendLine(
            $"**Progress:** {enabledCount}/{actions.Count} enabled; " +
            $"{actions.Count - enabledCount} gated.");
        builder.AppendLine();
        builder.AppendLine(
            "**Statuses:** " +
            string.Join(
                "; ",
                actions.GroupBy(action => action.ImplementationStatus)
                    .OrderBy(group => group.Key, StringComparer.Ordinal)
                    .Select(group => $"{group.Key}: {group.Count()}")) +
            ".");
        builder.AppendLine();
        builder.AppendLine(
            "**Planned tiers for gated actions:** " +
            string.Join(
                "; ",
                actions.Where(action => !action.IsAvailable)
                    .GroupBy(action => action.PlannedTier)
                    .OrderBy(group => group.Key, StringComparer.Ordinal)
                    .Select(group => $"{group.Key}: {group.Count()}")) +
            ".");
        builder.AppendLine();
        builder.AppendLine("| Action | Windows semantics and variants | Mac tier | Status | Evidence / version | Blocker | Planned tier | Acceptance fixture / command | Recovery / evidence gate |");
        builder.AppendLine("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
        foreach (var action in actions)
        {
            var semanticsAndVariants = new[] { action.WindowsSemantics }
                .Concat(action.WindowsVariants)
                .Select(EscapeMarkdown);
            var variants = string.Join("<br>", semanticsAndVariants);
            var status = action.IsAvailable
                ? $"{action.ImplementationStatus}; enabled"
                : $"{action.ImplementationStatus}; gated";
            builder.Append("| `")
                .Append(EscapeMarkdown(action.Command))
                .Append("` | ")
                .Append(variants)
                .Append(" | ")
                .Append(EscapeMarkdown(action.Tier))
                .Append(" | ")
                .Append(EscapeMarkdown(status))
                .Append(" | ")
                .Append(EscapeMarkdown($"{action.Evidence} {action.ExcelApiVersion}"))
                .Append(" | ")
                .Append(EscapeMarkdown(string.IsNullOrWhiteSpace(action.Blocker) ? "None." : action.Blocker))
                .Append(" | ")
                .Append(EscapeMarkdown(action.PlannedTier))
                .Append(" | ")
                .Append(EscapeMarkdown($"{action.AcceptanceFixture} {action.AcceptanceCommand}"))
                .Append(" | ")
                .Append(EscapeMarkdown($"{action.RecoveryRule} {action.EvidenceCriteria}"))
                .AppendLine(" |");
        }

        return builder.ToString();
    }

    private static string EscapeMarkdown(string value)
    {
        var escaped = value.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");
        return escaped.Replace("<", "&lt;").Replace(">", "&gt;");
    }

    private sealed class MacAction
    {
        public string Command { get; set; } = string.Empty;
        public string WindowsSemantics { get; set; } = string.Empty;
        public List<string> WindowsVariants { get; set; } = [];
        public string Tier { get; set; } = string.Empty;
        public bool IsAvailable { get; set; }
        public string ImplementationStatus { get; set; } = string.Empty;
        public string Evidence { get; set; } = string.Empty;
        public string ExcelApiVersion { get; set; } = string.Empty;
        public string Blocker { get; set; } = string.Empty;
        public string PlannedTier { get; set; } = string.Empty;
        public string AcceptanceFixture { get; set; } = string.Empty;
        public string AcceptanceCommand { get; set; } = string.Empty;
        public string RecoveryRule { get; set; } = string.Empty;
        public string EvidenceCriteria { get; set; } = string.Empty;
    }
}
