openapi: 3.0.0
info:
  title: ExcelMcp Rename Operations (Conceptual)
  version: 1.0.0
  description: |
    Documentation-only contract describing request/response shapes for rename operations.
    ExcelMcp is not an HTTP API; this file documents CLI/MCP inputs and JSON outputs.

components:
  schemas:
    RenameResult:
      type: object
      required: [success, objectType, oldName, newName]
      properties:
        success:
          type: boolean
        errorMessage:
          type: string
          nullable: true
        objectType:
          type: string
          enum: [power-query, data-model-table]
        oldName:
          type: string
        newName:
          type: string

    PowerQueryRenameRequest:
      type: object
      required: [excelPath, queryName, newName]
      properties:
        excelPath:
          type: string
        batchId:
          type: string
          nullable: true
        queryName:
          type: string
          description: Existing query name (old name)
        newName:
          type: string
          description: Desired new query name

    DataModelTableRenameRequest:
      type: object
      required: [excelPath, tableName, newName]
      properties:
        excelPath:
          type: string
        batchId:
          type: string
          nullable: true
        tableName:
          type: string
          description: Existing data model table name (old name)
        newName:
          type: string
          description: Desired new table name

x-mcp:
  tools:
    excel_powerquery:
      rename:
        requestSchema: '#/components/schemas/PowerQueryRenameRequest'
        responseSchema: '#/components/schemas/RenameResult'
    excel_datamodel:
      rename-table:
        requestSchema: '#/components/schemas/DataModelTableRenameRequest'
        responseSchema: '#/components/schemas/RenameResult'

x-cli:
  commands:
    - command: powerquery
      action: rename
      args:
        - --session
        - --query
        - --new-name
      response: RenameResult
    - command: datamodel
      action: rename-table
      args:
        - --session
        - --table
        - --new-name
      response: RenameResult
