using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Sbroenne.ExcelMcp.Generators.Cli;

/// <summary>
/// Generates CLI command classes and registration.
/// Coordinates with Core-generated ServiceRegistry to produce CLI commands.
/// </summary>
[Generator]
public class CliSettingsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Hard-coded categories matching Core's ServiceRegistry
        var categories = new[]
        {
            ("worksheet", "Sheet", true),
            ("worksheetstyle", "SheetStyle", true),
            ("range", "Range", true),
            ("rangeedit", "RangeEdit", true),
            ("rangeformat", "RangeFormat", true),
            ("rangelink", "RangeLink", true),
            ("table", "Table", true),
            ("tablecolumn", "TableColumn", true),
            ("powerquery", "PowerQuery", true),
            ("pivottable", "PivotTable", true),
            ("pivottablefield", "PivotTableField", true),
            ("pivottablecalc", "PivotTableCalc", true),
            ("chart", "Chart", true),
            ("chartconfig", "ChartConfig", true),
            ("connection", "Connection", true),
            ("calculationmode", "Calculation", true),
            ("namedrange", "NamedRange", true),
            ("conditionalformat", "ConditionalFormat", true),
            ("vba", "Vba", true),
            ("datamodel", "DataModel", true),
            ("datamodelrel", "DataModelRel", true),
            ("slicer", "Slicer", true)
        };

        context.RegisterSourceOutput(
            context.CompilationProvider,
            (spc, _) => Generate(categories, spc));
    }

    private static void Generate((string CliName, string RegistryName, bool RequiresSession)[] categories, SourceProductionContext context)
    {
        foreach (var (cliName, registryName, requiresSession) in categories)
        {
            var cmdCode = GenerateCommandClass(registryName, requiresSession);
            context.AddSource($"CliCommand.{registryName}.g.cs", SourceText.From(cmdCode, System.Text.Encoding.UTF8));
        }

        var regCode = GenerateRegistration(categories);
        context.AddSource("CliCommandRegistration.Generated.g.cs", SourceText.From(regCode, System.Text.Encoding.UTF8));
    }

    private static string GenerateCommandClass(string registryName, bool requiresSession)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Sbroenne.ExcelMcp.CLI.Infrastructure;");
        sb.AppendLine("using Sbroenne.ExcelMcp.Generated;");
        sb.AppendLine();
        sb.AppendLine("namespace Sbroenne.ExcelMcp.CLI.Generated;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {registryName}Command : ServiceCommandBase<ServiceRegistry.{registryName}.CliSettings>");
        sb.AppendLine("{");
        if (!requiresSession) sb.AppendLine("    protected override bool RequiresSession => false;");
        sb.AppendLine($"    protected override string? GetSessionId(ServiceRegistry.{registryName}.CliSettings settings) => settings.SessionId;");
        sb.AppendLine($"    protected override string? GetAction(ServiceRegistry.{registryName}.CliSettings settings) => settings.Action;");
        sb.AppendLine($"    protected override IReadOnlyList<string> ValidActions => ServiceRegistry.{registryName}.ValidActions;");
        sb.AppendLine($"    protected override (string command, object? args) Route(ServiceRegistry.{registryName}.CliSettings settings, string action) => ServiceRegistry.{registryName}.RouteFromSettings(action, settings);");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateRegistration((string CliName, string RegistryName, bool RequiresSession)[] categories)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Sbroenne.ExcelMcp.Generated;");
        sb.AppendLine("using Spectre.Console.Cli;");
        sb.AppendLine();
        sb.AppendLine("namespace Sbroenne.ExcelMcp.CLI.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class CliCommandRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static void RegisterCommands(IConfigurator config)");
        sb.AppendLine("    {");
        foreach (var (cliName, registryName, _) in categories.OrderBy(c => c.CliName))
            sb.AppendLine($"        config.AddCommand<{registryName}Command>(\"{cliName}\").WithDescription(ServiceRegistry.{registryName}.Description);");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }
}
