// <auto-generated by scripts/Update-MacAppleEventCodes.ps1 />
namespace Sbroenne.ExcelMcp.Service.Mac;

internal static class MacExcelDictionary
{
    internal const uint WorkbookClass = 0x58313431u;
    internal const uint WorksheetClass = 0x58775348u;
    internal const uint ChartSheetClass = 0x58635348u;
    internal const uint Calculation = 0x31323038u;
    internal const uint CalculationAutomatic = 0x023DEFF7u;
    internal const uint CalculationManual = 0x023DEFD9u;
    internal const uint CalculationSemiautomatic = 0x023E0002u;
    internal const uint CalculateSheetClass = 0x736D584Cu;
    internal const uint CalculateSheetId = 0x31313735u;
    internal const uint CalculateRangeClass = 0x7354424Cu;
    internal const uint CalculateRangeId = 0x31313735u;
    internal const uint RangeClass = 0x58313137u;
    internal const uint CellClass = 0x6363656Cu;
    internal const uint Formula2 = 0x32313232u;
    internal const uint Formula2R1C1 = 0x46327263u;
    internal const uint Value2 = 0x44505632u;
    internal const uint HasFormula = 0x31353733u;
    internal const uint MergeCells = 0x31353838u;
    internal const uint MergeArea = 0x31353837u;
    internal const uint FirstRowIndex = 0x58667258u;
    internal const uint FirstColumnIndex = 0x58666358u;
    internal const uint RowClass = 0x63726F77u;
    internal const uint ColumnClass = 0x63636F6Cu;
    internal const uint GetAddressClass = 0x7354424Cu;
    internal const uint GetAddressId = 0x31353135u;
    internal const uint AddressExternalParameter = 0x35313233u;
    internal const uint EvaluateClass = 0x736D584Cu;
    internal const uint EvaluateId = 0x32343335u;
    internal const uint EvaluateNameParameter = 0x706E616Du;
    internal const uint WindowClass = 0x6377696Eu;
    internal const uint Name = 0x706E616Du;
    internal const uint FullName = 0x31373733u;
    internal const uint ActiveSheet = 0x31313037u;
    internal const uint Visible = 0x70766973u;
    internal const uint SheetVisible = 0x0270FFFFu;
    internal const uint SheetHidden = 0x02710000u;
    internal const uint SheetVeryHidden = 0x02710002u;
    internal const uint CloseClass = 0x636F7265u;
    internal const uint CloseId = 0x636C6F73u;
    internal const uint MakeClass = 0x636F7265u;
    internal const uint MakeId = 0x6372656Cu;
    internal const uint MakeClassParameter = 0x6B6F636Cu;
    internal const uint MakeLocationParameter = 0x696E7368u;
    internal const uint CountClass = 0x636F7265u;
    internal const uint CountId = 0x636E7465u;
    internal const uint CountClassParameter = 0x6B6F636Cu;
    internal const uint RunMacroClass = 0x7354424Cu;
    internal const uint RunMacroId = 0x32363230u;
    internal const uint MacroArgument1 = 0x35303430u;
}
