name: Build

permissions:
  contents: read

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '**.csproj'
      - '**.sln'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - '**.csproj'
      - '**.sln'
      - 'Directory.Build.props'
      - 'Directory.Packages.props'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Verify build (no tests - requires Excel)
      run: |
        Write-Output "ℹ️ Note: Unit tests skipped in CI - they require Microsoft Excel"
        Write-Output "   Run 'dotnet test' locally with Excel installed for full validation"
      shell: pwsh
      
    - name: Test build output
      run: |
        # Check ExcelMcp.CLI main executable
        if (Test-Path "src/ExcelMcp.CLI/bin/Release/net8.0/ExcelMcp.CLI.exe") {
          Write-Output "✅ ExcelMcp.CLI.exe built successfully"
          $version = (Get-Item "src/ExcelMcp.CLI/bin/Release/net8.0/ExcelMcp.CLI.exe").VersionInfo.FileVersion
          Write-Output "Version: $version"
        } else {
          Write-Error "❌ ExcelMcp.CLI.exe not found"
          exit 1
        }
        
        # Check MCP Server executable
        if (Test-Path "src/ExcelMcp.McpServer/bin/Release/net8.0/ExcelMcp.McpServer.exe") {
          Write-Output "✅ ExcelMcp.McpServer.exe built successfully"
          $mcpVersion = (Get-Item "src/ExcelMcp.McpServer/bin/Release/net8.0/ExcelMcp.McpServer.exe").VersionInfo.FileVersion
          Write-Output "📦 MCP Server Version: $mcpVersion"
        } else {
          Write-Error "❌ ExcelMcp.McpServer.exe not found"
          exit 1
        }
        
        Write-Output "🎯 Both CLI and MCP Server ready for distribution"
      shell: pwsh
      
    - name: Upload CLI build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ExcelMcp-CLI-${{ github.sha }}
        path: src/ExcelMcp.CLI/bin/Release/net8.0/
        
    - name: Upload MCP Server build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ExcelMcp-MCP-Server-${{ github.sha }}
        path: src/ExcelMcp.McpServer/bin/Release/net8.0/